dist: bionic
language: julia
julia:
  - 1.7.0
script:
    - julia --project=. -e 'using Pkg; Pkg.instantiate()'
    - julia --project=. --threads=2 advanced_cli.jl example/example.json --output-summary=summary.jld2 --output-daily=daily.jld2
    - julia --project=. --threads=2 advanced_cli.jl example/example.toml --output-summary=summary.jld2 --output-daily=daily.jld2
